export const theNames = [
  {
    firstName: "Philip",
    lastName: "A",
    birthMonth: "December",
    birthDay: 26,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Lauren",
    lastName: "A",
    birthMonth: "March",
    birthDay: 1,
    birthYear: 1975,
    passedAway: null,
  },
  {
    firstName: "Paulette",
    lastName: "B (Charlebois)",
    birthMonth: "March",
    birthDay: 28,
    birthYear: null,
    passedAway: "3/10/23",
  },
  {
    firstName: "James",
    lastName: "B",
    birthMonth: "November",
    birthDay: 13,
    birthYear: null,
    passedAway: "6/13/11",
  },
  {
    firstName: "Sue",
    lastName: "B",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Anne",
    lastName: "B",
    birthMonth: "December",
    birthDay: 15,
    birthYear: 1973,
    passedAway: null,
  },
  {
    firstName: "Ruth",
    lastName: "C",
    birthMonth: "September",
    birthDay: 8,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Leah",
    lastName: "C",
    birthMonth: "October",
    birthDay: 3,
    birthYear: 1970,
    passedAway: null,
  },
  {
    firstName: "Robert",
    lastName: "C",
    birthMonth: "July",
    birthDay: 6,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "James",
    lastName: "C",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Helena",
    lastName: "D",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Anne",
    lastName: "D",
    birthMonth: "March",
    birthDay: 13,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "George",
    lastName: "D",
    birthMonth: "March",
    birthDay: 17,
    birthYear: 1941,
    passedAway: null,
  },
  {
    firstName: "Diane",
    lastName: "D (Hennessey)",
    birthMonth: "March",
    birthDay: 21,
    birthYear: 1942,
    passedAway: null,
  },
  {
    firstName: "Pat",
    lastName: "D",
    birthMonth: "December",
    birthDay: 25,
    birthYear: 1974,
    passedAway: null,
  },
  {
    firstName: "Leigh",
    lastName: "F",
    birthMonth: "November",
    birthDay: 21,
    birthYear: 1977,
    passedAway: null,
  },
  {
    firstName: "Maurice",
    lastName: "F",
    birthMonth: "March",
    birthDay: 21,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Rita",
    lastName: "H",
    birthMonth: "July",
    birthDay: 28,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Pat",
    lastName: "H",
    birthMonth: "June",
    birthDay: 25,
    birthYear: 1981,
    passedAway: null,
  },
  {
    firstName: "Mike",
    lastName: "H",
    birthMonth: "March",
    birthDay: 9,
    birthYear: 1984,
    passedAway: null,
  },
  {
    firstName: "Jack",
    lastName: "H",
    birthMonth: "April",
    birthDay: 14,
    birthYear: 1987,
    passedAway: null,
  },
  {
    firstName: "Daniel",
    lastName: "H",
    birthMonth: "July",
    birthDay: 27,
    birthYear: 1988,
    passedAway: null,
  },
  {
    firstName: "Marty",
    lastName: "H",
    birthMonth: "June",
    birthDay: 2,
    birthYear: 1948,
    passedAway: null,
  },
  {
    firstName: "John",
    lastName: "H",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Katherine",
    lastName: "H",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "John",
    lastName: "H",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Edith",
    lastName: "I",
    birthMonth: "March",
    birthDay: 22,
    birthYear: 1992,
    passedAway: null,
  },
  {
    firstName: "Christine",
    lastName: "I",
    birthMonth: "March",
    birthDay: 27,
    birthYear: 1966,
    passedAway: null,
  },
  {
    firstName: "Michael",
    lastName: "I",
    birthMonth: "July",
    birthDay: 5,
    birthYear: 1967,
    passedAway: null,
  },
  {
    firstName: "Shekar",
    lastName: "I",
    birthMonth: "July",
    birthDay: 14,
    birthYear: 1963,
    passedAway: null,
  },
  {
    firstName: "Kamal",
    lastName: "I",
    birthMonth: "July",
    birthDay: 28,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Mary",
    lastName: "I (Katherine Hennessey)",
    birthMonth: "August",
    birthDay: 9,
    birthYear: 1944,
    passedAway: null,
  },
  {
    firstName: "Bharathi",
    lastName: "I",
    birthMonth: "November",
    birthDay: 14,
    birthYear: 1958,
    passedAway: null,
  },
  {
    firstName: "Yogesh",
    lastName: "I",
    birthMonth: "December",
    birthDay: 20,
    birthYear: 2006,
    passedAway: null,
  },
  {
    firstName: "Ramanath A",
    lastName: "I",
    birthMonth: "December",
    birthDay: 25,
    birthYear: 1933,
    passedAway: null,
  },
  {
    firstName: "Balan",
    lastName: "I",
    birthMonth: "December",
    birthDay: 30,
    birthYear: 1964,
    passedAway: null,
  },
  {
    firstName: "Kuti",
    lastName: "I",
    birthMonth: "February",
    birthDay: 18,
    birthYear: 1958,
    passedAway: null,
  },
  {
    firstName: "Eshi",
    lastName: "I",
    birthMonth: "February",
    birthDay: 19,
    birthYear: 1954,
    passedAway: null,
  },
  {
    firstName: "Bharathi",
    lastName: "I",
    birthMonth: "February",
    birthDay: 2,
    birthYear: 1961,
    passedAway: null,
  },
  {
    firstName: "Amba",
    lastName: "I",
    birthMonth: "December",
    birthDay: 12,
    birthYear: 1954,
    passedAway: null,
  },
  {
    firstName: "Carolyn",
    lastName: "I (Anne Bignell)",
    birthMonth: "August",
    birthDay: 24,
    birthYear: 1973,
    passedAway: null,
  },
  {
    firstName: "Franky",
    lastName: "I (Luna)",
    birthMonth: "September",
    birthDay: 11,
    birthYear: 2023,
    passedAway: null,
  },
  {
    firstName: "Bob",
    lastName: "J",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Ryan",
    lastName: "J",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Alana",
    lastName: "J",
    birthMonth: "May",
    birthDay: 1,
    birthYear: 2025,
    passedAway: null,
  },
  {
    firstName: "Brigid",
    lastName: "K",
    birthMonth: "May",
    birthDay: 1,
    birthYear: 2025,
    passedAway: null,
  },
  {
    firstName: "Gerard",
    lastName: "K (Anthony)",
    birthMonth: "March",
    birthDay: 31,
    birthYear: 1969,
    passedAway: null,
  },
  {
    firstName: "Michael",
    lastName: "K",
    birthMonth: "November",
    birthDay: 11,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Wendy",
    lastName: "K",
    birthMonth: "January",
    birthDay: 9,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Maureen",
    lastName: "K",
    birthMonth: "June",
    birthDay: 4,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Dylan",
    lastName: "K",
    birthMonth: "September",
    birthDay: 10,
    birthYear: 2015,
    passedAway: null,
  },
  {
    firstName: "Deirdre",
    lastName: "K",
    birthMonth: "April",
    birthDay: 1,
    birthYear: 1959,
    passedAway: null,
  },
  {
    firstName: "Siobhan",
    lastName: "K",
    birthMonth: "April",
    birthDay: 1,
    birthYear: 1959,
    passedAway: null,
  },
  {
    firstName: "Grace",
    lastName: "K",
    birthMonth: "February",
    birthDay: 1,
    birthYear: 1961,
    passedAway: null,
  },
  {
    firstName: "Mary",
    lastName: "K",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Robert",
    lastName: "K",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Patricia",
    lastName: "K",
    birthMonth: "August",
    birthDay: 9,
    birthYear: 1974,
    passedAway: null,
  },
  {
    firstName: "Christine",
    lastName: "L",
    birthMonth: "January",
    birthDay: 6,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Courtney",
    lastName: "L",
    birthMonth: "January",
    birthDay: 12,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Riley",
    lastName: "L",
    birthMonth: "April",
    birthDay: 14,
    birthYear: 2009,
  },
  {
    firstName: "Eleanor",
    lastName: "L",
    birthMonth: "July",
    birthDay: 6,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "John, Jr.",
    lastName: "L",
    birthMonth: "July",
    birthDay: 10,
    birthYear: 2006,
    passedAway: null,
  },
  {
    firstName: "John",
    lastName: "L",
    birthMonth: "September",
    birthDay: 11,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Jake",
    lastName: "M",
    birthMonth: "December",
    birthDay: 22,
    birthYear: 1969,
    passedAway: null,
  },
  {
    firstName: "Oscar",
    lastName: "M",
    birthMonth: "February",
    birthDay: 16,
    birthYear: 2004,
    passedAway: null,
  },
  {
    firstName: "Razel",
    lastName: "M",
    birthMonth: "May",
    birthDay: 31,
    birthYear: 2001,
    passedAway: null,
  },
  {
    firstName: "Orozco",
    lastName: "M",
    birthMonth: "April",
    birthDay: 23,
    birthYear: 1966,
    passedAway: null,
  },
  {
    firstName: "Orozco",
    lastName: "M (Arvin)",
    birthMonth: "June",
    birthDay: 14,
    birthYear: 1972,
    passedAway: null,
  },
  {
    firstName: "Meredith",
    lastName: "M (Bannon)",
    birthMonth: "August",
    birthDay: 17,
    birthYear: null,
  },
  {
    firstName: "Corey",
    lastName: "M (Gray)",
    birthMonth: "September",
    birthDay: 25,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Josiah",
    lastName: "M",
    birthMonth: "January",
    birthDay: 13,
    birthYear: 1971,
    passedAway: null,
  },
  {
    firstName: "Shannon",
    lastName: "M (Beth McDonald)",
    birthMonth: "May",
    birthDay: 24,
    birthYear: 1970,
    passedAway: null,
  },
  {
    firstName: "Kai",
    lastName: "P",
    birthMonth: "February",
    birthDay: 25,
    birthYear: 1987,
    passedAway: null,
  },
  {
    firstName: "Eryn",
    lastName: "K",
    birthMonth: "January",
    birthDay: 8,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Charlie",
    lastName: "P",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
  },
  {
    firstName: "Louisa",
    lastName: "R",
    birthMonth: "October",
    birthDay: 17,
    birthYear: 2001,
    passedAway: null,
  },
  {
    firstName: "Naomi",
    lastName: "R",
    birthMonth: "July",
    birthDay: 21,
    birthYear: 1999,
    passedAway: null,
  },
  {
    firstName: "Jonathon",
    lastName: "R",
    birthMonth: "December",
    birthDay: 31,
    birthYear: 1965,
    passedAway: null,
  },
  {
    firstName: "Marino",
    lastName: "R",
    birthMonth: "September",
    birthDay: 16,
    birthYear: 1961,
    passedAway: null,
  },
  {
    firstName: "Lynne",
    lastName: "R",
    birthMonth: "December",
    birthDay: 21,
    birthYear: 1965,
    passedAway: null,
  },
  {
    firstName: "Oliver",
    lastName: "R",
    birthMonth: "January",
    birthDay: 21,
    birthYear: 2001,
    passedAway: null,
  },
  {
    firstName: "Paul",
    lastName: "R",
    birthMonth: "August",
    birthDay: 4,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Andrey",
    lastName: "R",
    birthMonth: "January",
    birthDay: 30,
    birthYear: 1988,
    passedAway: null,
  },
  {
    firstName: "Danika",
    lastName: "R",
    birthMonth: "March",
    birthDay: 10,
    birthYear: 2022,
    passedAway: null,
  },
  {
    firstName: "Lorelei",
    lastName: "R",
    birthMonth: "June",
    birthDay: 25,
    birthYear: 2018,
    passedAway: null,
  },
  {
    firstName: "Ophelia",
    lastName: "R",
    birthMonth: "August",
    birthDay: 22,
    birthYear: 2022,
    passedAway: null,
  },
  {
    firstName: "Carol",
    lastName: "S",
    birthMonth: "January",
    birthDay: 31,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Billie",
    lastName: "S (Ruth Sattar)",
    birthMonth: "August",
    birthDay: 2,
    birthYear: 1931,
    passedAway: null,
  },
  {
    firstName: "Bertha",
    lastName: "S",
    birthMonth: null,
    birthDay: null,
    birthYear: 1882,
    passedAway: null,
  },
  {
    firstName: "Joseph",
    lastName: "S",
    birthMonth: "January",
    birthDay: 6,
    birthYear: 1923,
    passedAway: null,
  },
  {
    firstName: "Roger",
    lastName: "S",
    birthMonth: "July",
    birthDay: 26,
    birthYear: 1926,
    passedAway: null,
  },
  {
    firstName: "Pamela",
    lastName: "S (Carver)",
    birthMonth: "August",
    birthDay: 9,
    birthYear: 1956,
    passedAway: null,
  },
  {
    firstName: "Selena",
    lastName: "S (Dorn)",
    birthMonth: "May",
    birthDay: 21,
    birthYear: 1978,
    passedAway: null,
  },
  {
    firstName: "Livia",
    lastName: "S (Dorn)",
    birthMonth: "September",
    birthDay: 10,
    birthYear: 1980,
    passedAway: null,
  },
  {
    firstName: "Tony",
    lastName: "S (Carver)",
    birthMonth: "August",
    birthDay: 9,
    birthYear: 2002,
    passedAway: null,
  },
  {
    firstName: "Isabel",
    lastName: "S",
    birthMonth: "August",
    birthDay: 9,
    birthYear: 2002,
    passedAway: null,
  },
  {
    firstName: "Patrick, Jr.",
    lastName: "S",
    birthMonth: "August",
    birthDay: 9,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Patrick",
    lastName: "S",
    birthMonth: "September",
    birthDay: 11,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Maryanne",
    lastName: "S",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Sloane",
    lastName: "S",
    birthMonth: "January",
    birthDay: 3,
    birthYear: null,
    passedAway: null,
  },

  {
    firstName: "John",
    lastName: "S",
    birthMonth: "July",
    birthDay: 31,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Omer",
    lastName: "T",
    birthMonth: "January",
    birthDay: 21,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Evangeline",
    lastName: "T",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Scott",
    lastName: "T",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Peter",
    lastName: "U (Michael)",
    birthMonth: "July",
    birthDay: 1,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Peggy",
    lastName: "U",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
  },
  {
    firstName: "Robert",
    lastName: "U",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
  },
  {
    firstName: "Robert, Jr.",
    lastName: "U",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Elizabeth",
    lastName: "U",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
  },
  {
    firstName: "Lisa",
    lastName: "W (Bignell)",
    birthMonth: "February",
    birthDay: 24,
    birthYear: 1975,
    passedAway: null,
  },
  {
    firstName: "Elise",
    lastName: "W",
    birthMonth: "July",
    birthDay: 24,
    birthYear: 2005,
    passedAway: null,
  },
  {
    firstName: "River",
    lastName: "W",
    birthMonth: "March",
    birthDay: 7,
    birthYear: 2007,
    passedAway: null,
  },
  {
    firstName: "Trevor",
    lastName: "W",
    birthMonth: "March",
    birthDay: 1,
    birthYear: 1969,
    passedAway: null,
  },
  {
    firstName: "Laura",
    lastName: "W",
    birthMonth: "December",
    birthDay: 31,
    birthYear: 1967,
    passedAway: null,
  },
  {
    firstName: "Steven",
    lastName: "C",
    birthMonth: "November",
    birthDay: 7,
    birthYear: 1968,
    passedAway: null,
  },
  {
    firstName: "Kimberly",
    lastName: "C",
    birthMonth: "November",
    birthDay: 14,
    birthYear: 1975,
    passedAway: null,
  },
  {
    firstName: "Jo-Ann",
    lastName: "C",
    birthMonth: "April",
    birthDay: 24,
    birthYear: 1976,
    passedAway: null,
  },
  {
    firstName: "Michael",
    lastName: "C",
    birthMonth: "October",
    birthDay: 14,
    birthYear: null,
    passedAway: null,
  },
];
