
export const theNames = [
  { firstName: "Philip", lastName: "A", birthMonth: "December", birthDay: 26, birthYear: null },
  { firstName: "Lauren", lastName: "A", birthMonth: "March", birthDay: 1, birthYear: 1975 },
  { firstName: "Paulette", lastName: "B (Charlebois)", birthMonth: "March", birthDay: 28, birthYear: null },
  { firstName: "James", lastName: "B", birthMonth: "November", birthDay: 13, birthYear: null },
  { firstName: "Sue", lastName: "B", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "Anne", lastName: "B", birthMonth: "December", birthDay: 15, birthYear: 1973 },
  { firstName: "Ruth", lastName: "C", birthMonth: "September", birthDay: 8, birthYear: null },
  { firstName: "Leah", lastName: "C", birthMonth: "October", birthDay: 3, birthYear: 1970 },
  { firstName: "Robert", lastName: "C", birthMonth: "July", birthDay: 6, birthYear: null },
  { firstName: "James", lastName: "C", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "Helena", lastName: "D", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "Anne", lastName: "D", birthMonth: "March", birthDay: 13, birthYear: null },
  { firstName: "George", lastName: "D", birthMonth: "March", birthDay: 17, birthYear: 1941 },
  { firstName: "Diane", lastName: "D (Hennessey)", birthMonth: "March", birthDay: 21, birthYear: 1942 },
  { firstName: "Pat", lastName: "D", birthMonth: "December", birthDay: 25, birthYear: 1974 },
  { firstName: "Leigh", lastName: "F", birthMonth: "November", birthDay: 21, birthYear: 1977 },
  { firstName: "Maurice", lastName: "F", birthMonth: "March", birthDay: 21, birthYear: null },
  { firstName: "Rita", lastName: "H", birthMonth: "July", birthDay: 28, birthYear: null },
  { firstName: "Pat", lastName: "H", birthMonth: "June", birthDay: 25, birthYear: 1981 },
  { firstName: "Mike", lastName: "H", birthMonth: "March", birthDay: 9, birthYear: 1984 },
  { firstName: "Jack", lastName: "H", birthMonth: "April", birthDay: 14, birthYear: 1987 },
  { firstName: "Daniel", lastName: "H", birthMonth: "July", birthDay: 27, birthYear: 1988 },
  { firstName: "Marty", lastName: "H", birthMonth: "June", birthDay: 2, birthYear: 1948 },
  { firstName: "John", lastName: "H", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "Katherine", lastName: "H", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "John", lastName: "H", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "Edith", lastName: "I", birthMonth: "March", birthDay: 22, birthYear: 1992 },
  { firstName: "Christine", lastName: "I", birthMonth: "March", birthDay: 27, birthYear: 1966 },
  { firstName: "Michael", lastName: "I", birthMonth: "July", birthDay: 5, birthYear: 1967 },
  { firstName: "Shekar", lastName: "I", birthMonth: "July", birthDay: 14, birthYear: 1963 },
  { firstName: "Kamal", lastName: "I", birthMonth: "July", birthDay: 28, birthYear: null },
  { firstName: "Mary", lastName: "I (Katherine Hennessey)", birthMonth: "August", birthDay: 9, birthYear: 1944 },
  { firstName: "Bharathi", lastName: "I", birthMonth: "November", birthDay: 14, birthYear: 1958 },
  { firstName: "Yogesh", lastName: "I", birthMonth: "December", birthDay: 20, birthYear: 2006 },
  { firstName: "Ramanath A", lastName: "I", birthMonth: "December", birthDay: 25, birthYear: 1933 },
  { firstName: "Balan", lastName: "I", birthMonth: "December", birthDay: 30, birthYear: 1964 },
  { firstName: "Kuti", lastName: "I", birthMonth: "February", birthDay: 18, birthYear: 1958 },
  { firstName: "Eshi", lastName: "I", birthMonth: "February", birthDay: 19, birthYear: 1954 },
  { firstName: "Bharathi", lastName: "I", birthMonth: "February", birthDay: 2, birthYear: 1961 },
  { firstName: "Amba", lastName: "I", birthMonth: "December", birthDay: 12, birthYear: 1954 },
  { firstName: "Carolyn", lastName: "I (Anne Bignell)", birthMonth: "August", birthDay: 24, birthYear: 1973 },
  { firstName: "Franky", lastName: "I (Luna)", birthMonth: "September", birthDay: 11, birthYear: 2023 },
  { firstName: "Bob", lastName: "J", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "Ryan", lastName: "J", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "Alana", lastName: "J", birthMonth: "May", birthDay: 1, birthYear: 2025 },
  { firstName: "Brigid", lastName: "K", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "Gerard", lastName: "K (Anthony)", birthMonth: "March", birthDay: 31, birthYear: 1969 },
  { firstName: "Michael", lastName: "K", birthMonth: "November", birthDay: 11, birthYear: null },
  { firstName: "Wendy", lastName: "K", birthMonth: "January", birthDay: 9, birthYear: null },
  { firstName: "Maureen", lastName: "K", birthMonth: "June", birthDay: 4, birthYear: null },
  { firstName: "Dylan", lastName: "K", birthMonth: "September", birthDay: 10, birthYear: 2015 },
  { firstName: "Deirdre", lastName: "K", birthMonth: "April", birthDay: 1, birthYear: 1959 },
  { firstName: "Siobhan", lastName: "K", birthMonth: "April", birthDay: 1, birthYear: 1959 },
  { firstName: "Grace", lastName: "K", birthMonth: "February", birthDay: 1, birthYear: 1961 },
  { firstName: "Mary", lastName: "K", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "Robert", lastName: "K", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "Patricia", lastName: "K", birthMonth: "August", birthDay: 9, birthYear: 1974 },
  { firstName: "Christine", lastName: "L", birthMonth: "January", birthDay: 6, birthYear: null },
  { firstName: "Courtney", lastName: "L", birthMonth: "January", birthDay: 12, birthYear: null },
  { firstName: "Riley", lastName: "L", birthMonth: "April", birthDay: 14, birthYear: 2009 },
  { firstName: "Eleanor", lastName: "L", birthMonth: "July", birthDay: 6, birthYear: null },
  { firstName: "John, Jr.", lastName: "L", birthMonth: "July", birthDay: 10, birthYear: 2006 },
  { firstName: "John", lastName: "L", birthMonth: "September", birthDay: 11, birthYear: null },
  { firstName: "Jake", lastName: "M", birthMonth: "December", birthDay: 22, birthYear: 1969 },
  { firstName: "Oscar", lastName: "M", birthMonth: "February", birthDay: 16, birthYear: 2004 },
  { firstName: "Razel", lastName: "M", birthMonth: "May", birthDay: 31, birthYear: 2001 },
  { firstName: "Orozco", lastName: "M", birthMonth: "April", birthDay: 23, birthYear: 1966 },
  { firstName: "Orozco", lastName: "M (Arvin)", birthMonth: "June", birthDay: 14, birthYear: 1972 },
  { firstName: "Meredith", lastName: "M (Bannon)", birthMonth: "August", birthDay: 17, birthYear: null },
  { firstName: "Corey", lastName: "M (Gray)", birthMonth: "September", birthDay: 25, birthYear: null },
  { firstName: "Josiah", lastName: "M", birthMonth: "January", birthDay: 13, birthYear: 1971 },
  { firstName: "Shannon", lastName: "M (Beth McDonald)", birthMonth: "May", birthDay: 24, birthYear: 1970 },
  { firstName: "Kai", lastName: "P", birthMonth: "February", birthDay: 25, birthYear: 1987 },
  { firstName: "Eryn", lastName: "K", birthMonth: "January", birthDay: 8, birthYear: null },
  { firstName: "Charlie", lastName: "P", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "Louisa", lastName: "R", birthMonth: "October", birthDay: 17, birthYear: 2001 },
  { firstName: "Naomi", lastName: "R", birthMonth: "July", birthDay: 21, birthYear: 1999 },
  { firstName: "Jonathon", lastName: "R", birthMonth: "December", birthDay: 31, birthYear: 1965 },
  { firstName: "Marino", lastName: "R", birthMonth: "September", birthDay: 16, birthYear: 1961 },
  { firstName: "Lynne", lastName: "R", birthMonth: "December", birthDay: 21, birthYear: 1965 },
  { firstName: "Oliver", lastName: "R", birthMonth: "January", birthDay: 21, birthYear: 2001 },
  { firstName: "Paul", lastName: "R", birthMonth: "August", birthDay: 4, birthYear: null },
  { firstName: "Andrey", lastName: "R", birthMonth: "January", birthDay: 30, birthYear: 1988 },
  { firstName: "Danika", lastName: "R", birthMonth: "March", birthDay: 10, birthYear: 2022 },
  { firstName: "Lorelei", lastName: "R", birthMonth: "June", birthDay: 25, birthYear: 2018 },
  { firstName: "Ophelia", lastName: "R", birthMonth: "August", birthDay: 22, birthYear: 2022 },
  { firstName: "Carol", lastName: "S", birthMonth: "January", birthDay: 31, birthYear: null },
  { firstName: "Billie", lastName: "S (Ruth Sattar)", birthMonth: "August", birthDay: 2, birthYear: 1931 },
  { firstName: "Bertha", lastName: "S", birthMonth: null, birthDay: null, birthYear: 1882 },
  { firstName: "Joseph", lastName: "S", birthMonth: "January", birthDay: 6, birthYear: 1923 },
  { firstName: "Roger", lastName: "S", birthMonth: "July", birthDay: 26, birthYear: 1926 },
  { firstName: "Pamela", lastName: "S (Carver)", birthMonth: "August", birthDay: 9, birthYear: 1956 },
  { firstName: "Selena", lastName: "S (Dorn)", birthMonth: "May", birthDay: 21, birthYear: 1978 },
  { firstName: "Livia", lastName: "S (Dorn)", birthMonth: "September", birthDay: 10, birthYear: 1980 },
  { firstName: "Tony", lastName: "S (Carver)", birthMonth: "August", birthDay: 9, birthYear: 2002 },
  { firstName: "Isabel", lastName: "S", birthMonth: "August", birthDay: 9, birthYear: 2002 },
  { firstName: "Patrick, Jr.", lastName: "S", birthMonth: "August", birthDay: 9, birthYear: null },
  { firstName: "Patrick", lastName: "S", birthMonth: "September", birthDay: 11, birthYear: null },
  { firstName: "Maryanne", lastName: "S", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "Sloane", lastName: "S", birthMonth: "January", birthDay: 3, birthYear: null },
  { firstName: "Jason", lastName: "S", birthMonth: "August", birthDay: 18, birthYear: null },
  { firstName: "John", lastName: "S", birthMonth: "July", birthDay: 31, birthYear: null },
  { firstName: "Omer", lastName: "T", birthMonth: "January", birthDay: 21, birthYear: null },
  { firstName: "Evangeline", lastName: "T", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "Scott", lastName: "T", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "Peter", lastName: "U (Michael)", birthMonth: "July", birthDay: 1, birthYear: null },
  { firstName: "Peggy", lastName: "U", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "Robert", lastName: "U", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "Robert, Jr.", lastName: "U", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "Elizabeth", lastName: "U", birthMonth: null, birthDay: null, birthYear: null },
  { firstName: "Lisa", lastName: "W (Bignell)", birthMonth: "February", birthDay: 24, birthYear: 1975 },
  { firstName: "Elise", lastName: "W", birthMonth: "July", birthDay: 24, birthYear: 2005 },
  { firstName: "River", lastName: "W", birthMonth: "March", birthDay: 7, birthYear: 2007 },
  { firstName: "Trevor", lastName: "W", birthMonth: "March", birthDay: 1, birthYear: 1969 },
  { firstName: "Laura", lastName: "W", birthMonth: "December", birthDay: 31, birthYear: 1967 },
  { firstName: "Steven", lastName: "C", birthMonth: "November", birthDay: 7, birthYear: 1968 },
  { firstName: "Kimberly", lastName: "C", birthMonth: "November", birthDay: 14, birthYear: 1975 },
  { firstName: "Jo-Ann", lastName: "", birthMonth: "April", birthDay: 24, birthYear: 1976 },
  { firstName: "Michael", lastName: "C", birthMonth: "October", birthDay: 14, birthYear: null }

  
];
