export const theNames = [
  {
    firstName: "Philip",
    lastName: "Aff",
    birthMonth: "December",
    birthDay: 26,
    birthYear: 1965,
    passedAway: null,
    comment: null,
    family:  null,
  },
  {
    firstName: "Lauren",
    lastName: "At",
    birthMonth: "March",
    birthDay: 1,
    birthYear: 1975,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Paulette",
    lastName: "B.",
    birthMonth: "March",
    birthDay: 28,
    birthYear: null,
    passedAway: "3/10/23",
    comment: "❤️",
    family: "Pet",
  },
  {
    firstName: "James",
    lastName: "B.",
    birthMonth: "November",
    birthDay: 13,
    birthYear: null,
    passedAway: "6/13/11",
    comment: "❤️",
    family: "Pet",
  },
  {
    firstName: "Sue",
    lastName: "Bl",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Chris",
    lastName: "Bo",
    birthMonth: "September",
    birthDay: 2,
    birthYear: 1969,
    passedAway: null,
    comment: "I take it you and your wife are still alive?",
    family: null,
  },
  {
    firstName: "Anne",
    lastName: "Br",
    birthMonth: "December",
    birthDay: 15,
    birthYear: 1973,
    passedAway: null,
    comment: "Carolyn's friend, loco?",
    family: null,
  },
  {
    firstName: "Ruth",
    lastName: "Ch",
    birthMonth: "September",
    birthDay: 8,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Leah",
    lastName: "Cop",
    birthMonth: "October",
    birthDay: 3,
    birthYear: 1970,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Robert",
    lastName: "Cou",
    birthMonth: "July",
    birthDay: 6,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "James",
    lastName: "Cur.",
    birthMonth: "January",
    birthDay: 3,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Helena",
    lastName: "Da.",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Anne",
    lastName: "DeP.",
    birthMonth: "March",
    birthDay: 13,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "George",
    lastName: "DeP.",
    birthMonth: "March",
    birthDay: 17,
    birthYear: 1941,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Diane",
    lastName: "DeP.",
    birthMonth: "March",
    birthDay: 21,
    birthYear: 1942,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Pat",
    lastName: "DeP.",
    birthMonth: "December",
    birthDay: 25,
    birthYear: 1974,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Leigh",
    lastName: "Fe.",
    birthMonth: "November",
    birthDay: 21,
    birthYear: 1977,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Maurice",
    lastName: "Fon.",
    birthMonth: "March",
    birthDay: 21,
    birthYear: null,
    passedAway: null,
    comment: "Flick",
    family: null,
  },
  {
    firstName: "Rita",
    lastName: "Hen.",
    birthMonth: "July",
    birthDay: 28,
    birthYear: 1919,
    passedAway: "September 5, 2012",
    comment: null,
    family: null,
  },
  {
    firstName: "Pat",
    lastName: "Hen.",
    birthMonth: "June",
    birthDay: 25,
    birthYear: 1981,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Mike",
    lastName: "Hen.",
    birthMonth: "March",
    birthDay: 9,
    birthYear: 1984,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Jack",
    lastName: "Hen.",
    birthMonth: "April",
    birthDay: 14,
    birthYear: 1987,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Daniel",
    lastName: "Hen.",
    birthMonth: "July",
    birthDay: 27,
    birthYear: 1988,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Marty",
    lastName: "Hen.",
    birthMonth: "June",
    birthDay: 2,
    birthYear: 1948,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Maureen",
    lastName: "Hen.",
    birthMonth: "June",
    birthDay: 18,
    birthYear: 1956,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "John",
    lastName: "Hen.",
    birthMonth: "November",
    birthDay: 6,
    birthYear: 1916,
    passedAway: "8/9/69",
    comment: "Grandfather",
    family: null,
  },
  {
    firstName: "Rose",
    lastName: "Hen.",
    birthMonth: "September",
    birthDay: 27,
    birthYear: 2023,
    passedAway: null,
    comment: "Daniel's Kid",
    family: null,
  },
  {
    firstName: "Katherine",
    lastName: "How.",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "John",
    lastName: "How.",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Edith",
    lastName: "I.",
    birthMonth: "March",
    birthDay: 22,
    birthYear: 1992,
    passedAway: null,
    comment: null,
    family: "My People",
  },
  {
    firstName: "Christine",
    lastName: "I.",
    birthMonth: "March",
    birthDay: 27,
    birthYear: 1966,
    passedAway: null,
    comment: null,
    family: "My People",
  },
  {
    firstName: "Michael",
    lastName: "I.",
    birthMonth: "July",
    birthDay: 5,
    birthYear: 1967,
    passedAway: null,
    comment: null,
    family: "My People",
  },
  {
    firstName: "Shekar",
    lastName: "I.",
    birthMonth: "July",
    birthDay: 14,
    birthYear: 1963,
    passedAway: null,
    comment: null,
    family: "My People",
  },
  {
    firstName: "Kamal",
    lastName: "I.",
    birthMonth: "July",
    birthDay: 28,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: "My People",
  },
  {
    firstName: "Mary",
    lastName: "I.",
    birthMonth: "August",
    birthDay: 9,
    birthYear: 1944,
    passedAway: null,
    comment: null,
    family: "My People",
  },
  {
    firstName: "Bharathi",
    lastName: "I.",
    birthMonth: "November",
    birthDay: 14,
    birthYear: 1958,
    passedAway: null,
    comment: null,
    family: "My People",
  },
  {
    firstName: "Yogesh",
    lastName: "I.",
    birthMonth: "December",
    birthDay: 20,
    birthYear: 2006,
    passedAway: null,
    comment: null,
    family: "My People",
  },
  {
    firstName: "Ramanath",
    lastName: "I.",
    birthMonth: "December",
    birthDay: 25,
    birthYear: 1933,
    passedAway: "1/12/16",
    comment: null,
    family: "My People",
  },
  {
    firstName: "Balan",
    lastName: "I.",
    birthMonth: "December",
    birthDay: 30,
    birthYear: 1964,
    passedAway: null,
    comment: null,
    family: "My People",
  },
  {
    firstName: "Kuti",
    lastName: "I.",
    birthMonth: "February",
    birthDay: 18,
    birthYear: 1958,
    passedAway: null,
    comment: null,
    family: "My People",
  },
  {
    firstName: "Eshi",
    lastName: "I.",
    birthMonth: "February",
    birthDay: 19,
    birthYear: 1954,
    passedAway: null,
    comment: null,
    family: "My People",
  },
  {
    firstName: "Bharathi",
    lastName: "I.",
    birthMonth: "February",
    birthDay: 2,
    birthYear: 1961,
    passedAway: null,
    comment: null,
    family: "My People",
  },
  {
    firstName: "Amba",
    lastName: "I.",
    birthMonth: "December",
    birthDay: 12,
    birthYear: 1954,
    passedAway: null,
    comment: null,
    family: "My People",
  },
  {
    firstName: "Carolyn",
    lastName: "I.",
    birthMonth: "August",
    birthDay: 24,
    birthYear: 1973,
    passedAway: null,
    comment: null,
    family: "Pet",
  },
  {
    firstName: "Franky",
    lastName: "I.",
    birthMonth: "September",
    birthDay: 11,
    birthYear: 2023,
    passedAway: null,
    comment: null,
    family: "My People",
  },
  {
    firstName: "Bob",
    lastName: "Jo",
    birthMonth: "August",
    birthDay: 3,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: "Jackal's People",
  },
  {
    firstName: "Ryan",
    lastName: "Jo",
    birthMonth: "September",
    birthDay: 18,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: "Jackal's People",
  },
  {
    firstName: "Alana",
    lastName: "Jo",
    birthMonth: "January",
    birthDay: 9,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: "Jackal's People",
  },
  {
    firstName: "Brigid",
    lastName: "Ke",
    birthMonth: "May",
    birthDay: 1,
    birthYear: 2025,
    passedAway: null,
    comment: null,
    family: "Jackal's People",
  },
  {
    firstName: "Gerard",
    lastName: "Ke",
    birthMonth: "March",
    birthDay: 31,
    birthYear: 1969,
    passedAway: "12/4/09",
    comment: null,
    family: "Jackal's People",
  },
  {
    firstName: "Michael",
    lastName: "Ke",
    birthMonth: "November",
    birthDay: 11,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: "Jackal's People",
  },
  {
    firstName: "Wendy",
    lastName: "Ke",
    birthMonth: "January",
    birthDay: 9,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: "Jackal's People",
  },
  {
    firstName: "Maureen",
    lastName: "Ke",
    birthMonth: "June",
    birthDay: 4,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: "Jackal's People",
  },
  {
    firstName: "Dylan",
    lastName: "Ke",
    birthMonth: "September",
    birthDay: 10,
    birthYear: 2015,
    passedAway: null,
    comment: null,
    family: "Jackal's People",
  },
  {
    firstName: "Deirdre",
    lastName: "Ke",
    birthMonth: "April",
    birthDay: 1,
    birthYear: 1959,
    passedAway: null,
    comment: null,
    family: "Jackal's People",
  },
  {
    firstName: "Siobhan",
    lastName: "Ke",
    birthMonth: "April",
    birthDay: 1,
    birthYear: 1959,
    passedAway: null,
    comment: null,
    family: "Jackal's People",
  },
  {
    firstName: "Grace",
    lastName: "Ke",
    birthMonth: "February",
    birthDay: 1,
    birthYear: 1961,
    passedAway: "11/4/2014",
    comment: null,
    family: "Jackal's People",
  },
  {
    firstName: "Mary",
    lastName: "Kel",
    birthMonth: "June",
    birthDay: 12,
    birthYear: 1923,
    passedAway: "8/11/2008",
    comment: null,
    family: null,
  },
  {
    firstName: "Robert",
    lastName: "Kel",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Patricia",
    lastName: "Ken",
    birthMonth: "August",
    birthDay: 9,
    birthYear: 1974,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Christine",
    lastName: "Lar",
    birthMonth: "January",
    birthDay: 6,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Courtney",
    lastName: "Lar",
    birthMonth: "January",
    birthDay: 12,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Riley ",
    lastName: "L",
    birthMonth: "April",
    birthDay: 14,
    birthYear: 2009,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Eleanor",
    lastName: "L",
    birthMonth: "July",
    birthDay: 6,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "John, Jr.",
    lastName: "Lar",
    birthMonth: "July",
    birthDay: 10,
    birthYear: 2006,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "John",
    lastName: "Lar",
    birthMonth: "September",
    birthDay: 11,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Jake",
    lastName: "McN",
    birthMonth: "December",
    birthDay: 22,
    birthYear: 1969,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Oscar",
    lastName: "McN",
    birthMonth: "February",
    birthDay: 16,
    birthYear: 2004,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Razel",
    lastName: "McN",
    birthMonth: "May",
    birthDay: 31,
    birthYear: 2001,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Gelaine",
    lastName: "Oro",
    birthMonth: "April",
    birthDay: 23,
    birthYear: 1966,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Duane",
    lastName: "Oro",
    birthMonth: "June",
    birthDay: 14,
    birthYear: 1972,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Meredith",
    lastName: "Squ",
    birthMonth: "August",
    birthDay: 17,
    birthYear: null,
    passedAway: null,
    comment: "Not Jason's wife, but partner",
    family: null,
  },
  {
    firstName: "Corey",
    lastName: "Mar",
    birthMonth: "September",
    birthDay: 25,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Josiah",
    lastName: "Mur",
    birthMonth: "January",
    birthDay: 13,
    birthYear: 1971,
    passedAway: null,
    comment: "Al Olander",
    family: null,
  },
  {
    firstName: "Shannon",
    lastName: "McD",
    birthMonth: "May",
    birthDay: 24,
    birthYear: 1970,
    passedAway: null,
    comment: "Tessie Olander",
    family: null,
  },
  {
    firstName: "Kai",
    lastName: "P.W.",
    birthMonth: "February",
    birthDay: 25,
    birthYear: 1987,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Eryn",
    lastName: "Ke",
    birthMonth: "January",
    birthDay: 8,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Charlie",
    lastName: "Poo",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Louisa",
    lastName: "Rad",
    birthMonth: "October",
    birthDay: 17,
    birthYear: 2001,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Naomi",
    lastName: "Rad",
    birthMonth: "July",
    birthDay: 21,
    birthYear: 1999,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Jonathon",
    lastName: "Rad",
    birthMonth: "December",
    birthDay: 31,
    birthYear: 1965,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Marino",
    lastName: "Ros",
    birthMonth: "September",
    birthDay: 16,
    birthYear: 1961,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Lynne",
    lastName: "Row",
    birthMonth: "December",
    birthDay: 21,
    birthYear: 1965,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Oliver",
    lastName: "Roy",
    birthMonth: "January",
    birthDay: 21,
    birthYear: 2001,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Paul",
    lastName: "Roy",
    birthMonth: "August",
    birthDay: 4,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Andrey",
    lastName: "Roy",
    birthMonth: "January",
    birthDay: 30,
    birthYear: 1988,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Danika",
    lastName: "Roy",
    birthMonth: "March",
    birthDay: 10,
    birthYear: 2022,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Lorelei",
    lastName: "Roy",
    birthMonth: "June",
    birthDay: 25,
    birthYear: 2018,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Ophelia",
    lastName: "Roy",
    birthMonth: "August",
    birthDay: 22,
    birthYear: 2022,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Carol",
    lastName: "Sit",
    birthMonth: "January",
    birthDay: 31,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Naomi",
    lastName: "Ske",
    birthMonth: "November",
    birthDay: 11,
    birthYear: 2008,
    passedAway: null,
    comment: "Livia's kid 1",
    family: null,
  },
  {
    firstName: "Fiona",
    lastName: "Ske",
    birthMonth: "March",
    birthDay: 31,
    birthYear: 2010,
    passedAway: null,
    comment: "Livia's kid 2",
    family: null,
  },
  {
    firstName: "Luna",
    lastName: "Ske",
    birthMonth: "March",
    birthDay: 4,
    birthYear: 2011,
    passedAway: null,
    comment: "Selena's kid 1",
    family: null,
  },
  {
    firstName: "Leo",
    lastName: "Ske",
    birthMonth: "July",
    birthDay: 24,
    birthYear: 2010,
    passedAway: null,
    comment: "Selena's kid 2",
    family: null,
  },
  {
    firstName: "Billie",
    lastName: "Ske",
    birthMonth: "August",
    birthDay: 2,
    birthYear: 1931,
    passedAway: "October 27, 2022",
    comment: "The Good William",
    family: null,
  },
  {
    firstName: "Bertha",
    lastName: "Ske",
    birthMonth: null,
    birthDay: null,
    birthYear: 1882,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Joseph",
    lastName: "Ske",
    birthMonth: "January",
    birthDay: 6,
    birthYear: 1923,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Roger",
    lastName: "Ske",
    birthMonth: "July",
    birthDay: 26,
    birthYear: 1926,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Pamela",
    lastName: "Ske",
    birthMonth: "August",
    birthDay: 9,
    birthYear: 1956,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Selena",
    lastName: "Ske",
    birthMonth: "May",
    birthDay: 21,
    birthYear: 1978,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Livia",
    lastName: "Ske",
    birthMonth: "September",
    birthDay: 10,
    birthYear: 1980,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Tony",
    lastName: "Ske",
    birthMonth: "August",
    birthDay: 9,
    birthYear: 2002,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Isabel",
    lastName: "Ske",
    birthMonth: "August",
    birthDay: 9,
    birthYear: 2002,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Patrick, Jr.",
    lastName: "Ske",
    birthMonth: "August",
    birthDay: 9,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Patrick",
    lastName: "Ske",
    birthMonth: "September",
    birthDay: 11,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Maryanne",
    lastName: "Ske",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Sloane",
    lastName: "Squ",
    birthMonth: "January",
    birthDay: 3,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Jason",
    lastName: "Squ",
    birthMonth: "August",
    birthDay: 18,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "John",
    lastName: "Stewart",
    birthMonth: "July",
    birthDay: 31,
    birthYear: 1969,
    passedAway: "Ok, he's alive but dead in terms of brain power",
    comment:
      "A nice guy but not particularly bright - Worried too much about trans stuff and in love with Trump - gross!",
    family: null,
  },
  {
    firstName: "Omer",
    lastName: "T",
    birthMonth: "January",
    birthDay: 21,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Evangeline",
    lastName: "T",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Scott",
    lastName: "T",
    birthMonth: null,
    birthDay: null,
    birthYear: 1969,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Peter",
    lastName: "Und",
    birthMonth: "July",
    birthDay: 1,
    birthYear: null,
    passedAway: "July 11, 2003",
    comment:
      "You and that asshole Bob Harvey shouldn't have ganged up on me. That was low rent man.",
    family: null,
  },
  {
    firstName: "Peggy",
    lastName: "Und",
    birthMonth: "April",
    birthDay: 7,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Robert",
    lastName: "Und",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Robert, Jr.",
    lastName: "Und",
    birthMonth: "May",
    birthDay: 23,
    birthYear: 1967,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Elizabeth",
    lastName: "Und",
    birthMonth: "April",
    birthDay: 25,
    birthYear: 1966,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Nancy",
    lastName: "Und",
    birthMonth: "Feb",
    birthDay: 22,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: null,
  },
  {
    firstName: "Lisa",
    lastName: "Wil",
    birthMonth: "February",
    birthDay: 24,
    birthYear: 1975,
    passedAway: null,
    comment: null,
    family: "Pet",
  },
  {
    firstName: "Elise",
    lastName: "Wil",
    birthMonth: "July",
    birthDay: 24,
    birthYear: 2005,
    passedAway: null,
    comment: null,
    family: "Pet",
  },
  {
    firstName: "River",
    lastName: "Wil",
    birthMonth: "March",
    birthDay: 7,
    birthYear: 2007,
    passedAway: null,
    comment: null,
    family: "Pet",
  },
  {
    firstName: "Trevor",
    lastName: "Wil",
    birthMonth: "March",
    birthDay: 1,
    birthYear: 1969,
    passedAway: null,
    comment: null,
    family: "Pet",
  },
  {
    firstName: "Laura",
    lastName: "Wil",
    birthMonth: "December",
    birthDay: 31,
    birthYear: 1967,
    passedAway: null,
    comment: null,
    family: "T'sut",
  },
  {
    firstName: "Len",
    lastName: "Wil",
    birthMonth: "August",
    birthDay: 29,
    birthYear: 1937,
    passedAway: "March 17, 2025",
    comment: "Laura's Dad - A good man",
    family: "T'sut",
  },
  {
    firstName: "Steven",
    lastName: "Cy",
    birthMonth: "November",
    birthDay: 7,
    birthYear: 1968,
    passedAway: null,
    comment: null,
    family: "Random",
  },
  {
    firstName: "Kimberly",
    lastName: "Cy",
    birthMonth: "November",
    birthDay: 14,
    birthYear: 1975,
    passedAway: null,
    comment: null,
    family: "Random",
  },
  {
    firstName: "Jo-Ann",
    lastName: "Cy",
    birthMonth: "April",
    birthDay: 24,
    birthYear: 1966,
    passedAway: null,
    comment: null,
    family: "Random",
  },
  {
    firstName: "Max",
    lastName: "Cy",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: 2010,
    comment: "Dog - Dead",
    family: "Random",
  },
  {
    firstName: "Michael",
    lastName: "Cy",
    birthMonth: "October",
    birthDay: 14,
    birthYear: null,
    passedAway: null,
    comment: null,
    family: "Random",
  },
  {
    firstName: "Jesus H.",
    lastName: "Christ",
    birthMonth: "December",
    birthDay: 25,
    birthYear: "BC 0005",
    passedAway: "AD 0033",
    comment: "Who really knows dates when it comes to this mysterious dude?",
    family: null,
  },
  {
    firstName: "Easter Bunny",
    lastName: "Jones",
    birthMonth: "April",
    birthDay: "Fluctuating date",
    birthYear: "Unknown Year",
    passedAway: "Unknown Year",
    comment: "This happy bastard loves hopping around like a fool",
    family: null,
  },
];
